global:
  scrape_interval:     15s
  evaluation_interval: 30s

rule_files:
  - alert.rules.yml

scrape_configs:
  - job_name: 'node'
    static_configs:
    - targets: ['server-01:9100']
    - targets: ['server-02:9100']
      labels:
        group: 'production'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
